### ISSUE TITLE
Input file not found

### ISSUE THREAD

**Issue by Brendan-Higgins** [halmaia/SL3Reader#3]
Hello,
I am interested in using you app to read some .sl3 files. When I run in in visual studio I get the following error message:

Input file not found!

C:\Users\Brendan\Source\Repos\SL3Reader\bin\Debug\net7.0\SL3Reader.exe (process 23612) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.

I see that it creates an .exe file in the above folder but it doesn't seem to open. Any insights would be appreciated.
Thank you

**Comment by halmaia** [comment]
Hi,

I uploaded a new version. Now, you have two options:
1. If you run the app from console (not from Visual Studio) you can use these patterns:
   To export 3D points:  SL3Reader.exe "C:\input.sl3" "D:\output.csv" -3d
   To export route:         SL3Reader.exe "C:\input.sl3" "D:\output.csv" -route
2. If you run the app from Visual Studio change the launchSettings.json file in the Properties folder according to the previous point. There should be a lot of fancy backslashes to escape qoutation marks.

There will be new release in the near future to make things easier.

Best regards,
Ákos Halmai

**Comment by halmaia** [comment]
Meanwhile I published the release. Take a look.
